apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bucket
  namespace: "{{namespace}}"
spec:
  selector:
    matchLabels:
      app: discord-bucket
  replicas: 1
  template:
    metadata:
      labels:
        app: discord-bucket
    spec:
      containers:
      - name: discord-bucket
        image: oxyl/discord-bucket:{{tag}}
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: environment
                key: node
          - name: TOKEN
            valueFrom: 
              secretKeyRef:
                name: discord
                key: token
          - name: REDIS_DATABASE
            value: "0"