apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: "{{namespace}}"
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: oxyl/gateway:{{tag}}
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: environment
                key: node
          - name: PG_DATABASE
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: database
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: user
          - name: PG_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: postgres
                key: password
          - name: PG_HOST
            value: "postgres-service"
          - name: PG_PORT
            value: "5432"
          - name: CACHE_SOCKET_ADDRESS
            value: "tcp://gateway-cache-zmq-proxy-service:8903"
          - name: API_PORT
            value: "8500"
        ports:
        - containerPort: 8500
          name: rest-api