apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-handler
  namespace: "{{namespace}}"
spec:
  selector:
    matchLabels:
      app: message-handler
  replicas: 1
  template:
    metadata:
      labels:
        app: message-handler
    spec:
      containers:
      - name: message-handler
        image: oxyl/message-handler:{{tag}}
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: config
                key: environment
          - name: BOT_ID
            valueFrom:
              configMapKeyRef:
                name: config
                key: clientID