apiVersion: apps/v1
kind: Deployment
metadata:
  name: shard-orchestrator
  namespace: "{{namespace}}"
spec:
  selector:
    matchLabels:
      app: shard-orchestrator
  replicas: 1
  template:
    metadata:
      labels:
        app: shard-orchestrator
    spec:
      containers:
      - name: shard-orchestrator
        image: oxyl/shard-orchestrator:{{tag}}
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: environment
                key: node
          - name: SHARDS_PER_SHARDER
            value: "5"
          - name: REDIS_DATABASE
            value: "1"