apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sharder
  namespace: "{{namespace}}"
spec:
  selector:
    matchLabels:
      app: sharder
  replicas: 0
  serviceName: "shard-orchestrator-service"
  template:
    metadata:
      labels:
        app: sharder
    spec:
      containers:
      - name: sharder
        image: oxyl/sharder:{{tag}}
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: environment
                key: node
          - name: TOKEN
            valueFrom: 
              secretKeyRef:
                name: discord
                key: token
          - name: CACHE_SOCKET_ADDRESS
            value: "tcp://gateway-cache-zmq-proxy-service:8902"
          - name: MESSAGE_SOCKET_ADDRESS
            value: "tcp://sharder-messages-zmq-proxy-service:8904"
          - name: ORCHESTRATOR_API
            value: "http://shard-orchestrator-service:8501/"
          - name: GATEWAY_API
            value: "http://gateway-service:8500/"