apiVersion: apps/v1
kind: Deployment
metadata:
  name: shard-orchestrator-deployment
  namespace: "{{namespace}}"
spec:
  selector:
    matchLabels:
      app: shard-orchestrator
  replicas: 1
  serviceName: shard-orchestrator-service
  template:
    metadata:
      labels:
        app: shard-orchestrator
    spec:
      containers:
      - name: shard-orchestrator
        image: oxyl/shard-orchestrator:{{tag}}
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: environment
                key: node
          - name: BUCKET_SOCKET_ADDRESS
            value: "tcp://discord-bucket-zmq-proxy-service:8900"
          - name: REDIS_DATABASE
            value: "1"
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "8379"
          - name: API_PORT
            value: "8501"