apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: "{{namespace}}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "{{dashboard_hostname}}"
    http:
      paths:
      - path: /
        backend:
          serviceName: dashboard
          servicePort: 8502