apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: "{{namespace}}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - hosts:
      - temp.minemidnight.work
      - oxyl.org
      - alpha.oxyl.org
      - beta.oxyl.org
    http:
      paths:
      - path: /
        backend:
          serviceName: dashboard
          servicePort: 8502