apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume
  namespace: "{{namespace}}"
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/postgres_data/{{namespace}}
    server: 172.17.0.2