kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sharder-binding
  namespace: "{{namespace}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sharder-scaling
subjects:
  - kind: ServiceAccount
    name: sharder-scaling
    namespace: "{{namespace}}"