kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{namespace}}
  name: sharder-scaling
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets", "statefulsets/status"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create"]