kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: sharder-scaling
rules:
- apiGroups: ["apps"]
  resources:
  - "statefulsets/scale"
  verbs:
  - patch
  - update