apiVersion: v1
kind: Service
metadata:
  name: discord-bucket-zmq-proxy
  namespace: "{{namespace}}"
spec:
  selector:
    app: discord-bucket-zmq-proxy
  ports:
    - name: router
      port: 8900
      protocol: "TCP"
    - name: dealer
      port: 8901
      protocol: "TCP"