apiVersion: v1
kind: Service
metadata:
  name: event-handler-zmq-proxy
  namespace: "{{namespace}}"
spec:
  selector:
    app: event-handler-zmq-proxy
  ports:
    - name: pull
      port: 8906
      protocol: "TCP"
    - name: push
      port: 8907
      protocol: "TCP"