apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway-pod
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: oxyl/gateway
        ports:
        - name: gRPC communication
          protocol: TCP
          containerPort: 8901
        - name: rest communication
          protocol: TPC
          containerPort: 8900
