apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharder-deployment
  labels:
    app: sharder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharder
  template:
    metadata:
      name: sharder-pod
      labels:
        app: sharder
    spec:
      containers:
      - name: sharder
        image: oxyl/sharder
        ports:
        - name: gRPC communication
          protocol: TCP
          containerPort: 8901
        - name: discord API
          protocol: TPC
          containerPort: 80
