apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: commands-autoscale
  labels:
    app: commands
spec:
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: commands-deployment
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 10
