apiVersion: v1
kind: Service
metadata:
  name: shard-orchestrator
  namespace: "{{namespace}}"
spec:
  selector:
    app: shard-orchestrator
  ports:
    - name: http
      port: 8501
      protocol: "TCP"