apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bucket-zmq-proxy
  namespace: "{{namespace}}"
spec:
  selector:
    matchLabels:
      app: discord-bucket-zmq-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: discord-bucket-zmq-proxy
        zmq-proxy: "true"
    spec:
      containers:
      - name: discord-bucket-zmq-proxy
        image: oxyl/zmq-proxy:{{tag}}
        imagePullPolicy: Always
        env:
          - name: INCOMING_ADDRESS
            value: "tcp://127.0.0.1:8900"
          - name: OUTGOING_ADDRESS
            value: "tcp://127.0.0.1:8901"
          - name: INCOMING_TYPE
            value: "6"
          - name: OUTGOING_TYPE
            value: "5"
        ports:
        - containerPort: 8900
          name: incoming
        - containerPort: 8901
          name: outgoing