apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-handler-zmq-proxy
  namespace: "{{namespace}}"
spec:
  selector:
    matchLabels:
      app: event-handler-zmq-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: event-handler-zmq-proxy
        zmq-proxy: "true"
    spec:
      containers:
      - name: event-handler-zmq-proxy
        image: oxyl/zmq-proxy:{{tag}}
        imagePullPolicy: Always
        env:
          - name: INCOMING_ADDRESS
            value: "tcp://0.0.0.0:8906"
          - name: OUTGOING_ADDRESS
            value: "tcp://0.0.0.0:8907"
          - name: INCOMING_TYPE
            value: "7"
          - name: OUTGOING_TYPE
            value: "8"
        ports:
        - containerPort: 8906
          name: incoming
        - containerPort: 8907
          name: outgoing