apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharder-messages-zmq-proxy
  namespace: "{{namespace}}"
spec:
  selector:
    matchLabels:
      app: sharder-messages-zmq-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: sharder-messages-zmq-proxy
        zmq-proxy: "true"
    spec:
      containers:
      - name: sharder-messages-zmq-proxy
        image: oxyl/zmq-proxy:{{tag}}
        imagePullPolicy: Always
        env:
          - name: INCOMING_ADDRESS
            value: "tcp://0.0.0.0:8904"
          - name: OUTGOING_ADDRESS
            value: "tcp://0.0.0.0:8905"
          - name: INCOMING_TYPE
            value: "7"
          - name: OUTGOING_TYPE
            value: "8"
        ports:
        - containerPort: 8904
          name: incoming
        - containerPort: 8905
          name: outgoing