apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharder-messages-zmq-proxy-deployment
  namespace: "{{namespace}}"
spec:
  selector:
    matchLabels:
      app: sharder-messages-zmq-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: sharder-messages-zmq-proxy
        zmq-proxy: true
    spec:
      containers:
      - name: sharder-messages-zmq-proxy
        image: oxyl/zmq-proxy
        env:
          - name: INCOMING_ADDRESS
            value: "tcp://127.0.0.1:8904"
          - name: OUTGOING_ADDRESS
            value: "tcp://127.0.0.1:8905"
          - name: INCOMING_TYPE
            value: 7
          - name: OUTGOING_TYPE
            value: 8
        ports:
        - incoming: 8904
        - outgoing: 8905