kind: Service
apiVersion: v1
metadata:
  name: gateway-service
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
  - name: gRPC communication
    protocol: TCP
    port: 8901
    targetPort: 8901
  - name: rest communication
    protocol: TPC
    port: 8900
    targetPort: 8900
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway-pod
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: oxyl/gateway
        ports:
        - name: gRPC communication
          protocol: TCP
          containerPort: 8901
        - name: rest communication
          protocol: TPC
          containerPort: 8900
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-autoscale
  labels:
    app: gateway
spec:
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: gateway-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
